flask/website/views.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from .crawling.antara_news import crawl_antara_news
from .crawling.detik_oto import crawl_detik_oto
from .models import CrawlingData
from . import db
from .plot import create_figure_pemberitaan, create_bar_chart_media, create_pie_chart_author
import io
import base64
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
import matplotlib.pyplot as plt

views = Blueprint('views', __name__)

# @views.route('/', methods=['GET', 'POST'])
# def home():
#     if request.method == 'POST':
#         data = request.form
#         tanggal = data.get('tanggal')
#         # filter data by date
#         crawl_data = CrawlingData.query.filter_by(created_at=tanggal).all()
#         home_data = create_data_home(crawl_data)
#         return render_template("home.html", home_data=home_data, crawl_data=crawl_data)
        
#     crawl_data = CrawlingData.query.all()
#     home_data = create_data_home(crawl_data)
#     return render_template("home.html", home_data=home_data, crawl_data=crawl_data)

@views.route('/', methods=['GET', 'POST'])
def home():
    if request.method == 'POST':
        data = request.form
        tanggal = data.get('tanggal')
        # add time to date
        tanggal = tanggal + " 00:00:00"
        # filter data by date from tanggal to todays date
        crawl_data = CrawlingData.query.filter(CrawlingData.created_at >= tanggal).all()
        print(f"tanggal: {tanggal}")
        home_data = create_data_home(crawl_data)
    else:
        # Default view (without filtering)
        crawl_data = CrawlingData.query.all()
        home_data = create_data_home(crawl_data)

    # Create the plots using home_data
    plot_pemberitaan = create_figure_pemberitaan(home_data)  # Line chart for berita
    plot_media = create_bar_chart_media(home_data)  # Bar chart for media
    plot_author = create_pie_chart_author(home_data)  # Pie chart for author

    # Convert figures to images
    output_pemberitaan = io.BytesIO()
    FigureCanvas(plot_pemberitaan).print_png(output_pemberitaan)
    pemberitaan = base64.b64encode(output_pemberitaan.getvalue()).decode('utf8')
    
    output_media = io.BytesIO()
    FigureCanvas(plot_media).print_png(output_media)
    output_media = base64.b64encode(output_media.getvalue()).decode('utf8')
    
    output_author = io.BytesIO()
    FigureCanvas(plot_author).print_png(output_author)
    output_author = base64.b64encode(output_author.getvalue()).decode('utf8')

    # Pass images as base64 encoded strings to the template (optional for inline display)
    return render_template("home.html", home_data=home_data,
                            crawl_data=crawl_data,
                            plot_pemberitaan=pemberitaan,
                            plot_media=output_media,
                            plot_author=output_author)


@views.route('/crawl')
def crawl():
    # crawl_data = CrawlingData.query.all()
    # get crawl data from database order by news_date
    crawl_data = CrawlingData.query.order_by(CrawlingData.news_date.desc()).all()
    return render_template("crawl.html", crawl_data=crawl_data)

@views.route('/sentiment')
def sentiment():
    crawl_data = CrawlingData.query.all()
    return render_template("sentiment.html", crawl_data=crawl_data)

@views.route('/crawl_add', methods=['GET', 'POST'])
def crawl_add():
    data = request.form
    start_date = data.get('start_date')
    end_date = data.get('end_date')
    media = data.getlist('media')
    keyword = data.getlist('keyword')
    antara = []
    detik = []
    if 'antara' in media:
        for key in keyword:
            data = crawl_antara_news(key, start_page=1, end_page=5, start_date_str=start_date, end_date_str=end_date)
            antara.append(data)
    if 'detikoto' in media:
        for key in keyword:
            data = crawl_detik_oto(key, start_page=1, end_page=5, start_date_str=start_date, end_date_str=end_date)
            detik.append(data)

    if antara or detik:
        flash("Crawling data successfully!", category="success")
        return redirect(url_for('views.crawl'))
    else:
        flash("Failed to crawl data.", category="error")

    return render_template("crawladd.html")


def create_data_home(crawl_data):
    # sum of news value
    sum_news_value = 0
    for data in crawl_data:
        sum_news_value += data.news_value
    
    # count of news
    count_news = len(crawl_data)

    # sum news group by created_at
    created_at = {}
    for data in crawl_data:
        if data.created_at in created_at:
            created_at[data.created_at] += 1
        else:
            created_at[data.created_at] = 1

    # sum news group by media
    media = {}
    for data in crawl_data:
        if data.media in media:
            media[data.media] += 1
        else:
            media[data.media] = 1
    
    # sum news group by author select only top 5
    author = {}
    for data in crawl_data:
        if data.author in author:
            author[data.author] += 1
        else:
            author[data.author] = 1
    author = dict(sorted(author.items(), key=lambda item: item[1], reverse=True)[:5])

    # create dictionary
    data_home = {
        'created_at': created_at,
        'media': media,
        'author': author,
        'sum_news_value': sum_news_value,
        'count_news': count_news
    }

    return data_home
    

flask/website/templates/base.html
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="" />
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors" />
        <meta name="generator" content="Hugo 0.84.0" />
        <title>Hyundai Gowa</title>

        <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sidebars/" />

        <!-- Bootstrap core CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css" />

        <!-- Favicons -->
        <meta name="theme-color" content="#7952b3" />

        <style>
            .bd-placeholder-img {
                font-size: 1.125rem;
                text-anchor: middle;
                -webkit-user-select: none;
                -moz-user-select: none;
                user-select: none;
            }

            @media (min-width: 768px) {
                .bd-placeholder-img-lg {
                    font-size: 3.5rem;
                }
            }
        </style>

        {% block style %}
                        
        {% endblock %}

        <!-- Custom styles for this template -->
        <!-- <link href="sidebars.css" rel="stylesheet" /> -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/sidebar.css') }}">
    </head>
    <body>

        <main>
            <div class="d-flex flex-column flex-shrink-0 p-3 text-white" style="width: 17rem; background-color: #1C2D5B;">
                <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                    <img src="{{ url_for('static', filename='img/logo2.png') }}" alt="" style="width: 14.3125rem;height: 1.52631rem;flex-shrink: 0;" class="mb-4">
                </a>
                <hr />
                <ul class="nav nav-pills flex-column mb-auto">
                    <li class="nav-item">
                        <a href="/" class="nav-link text-white {{ 'active' if active_page=='home' else ''}}">
                            <i class="fa-solid fa-house"></i>
                            Home
                        </a>
                    </li>
                    <li>
                        <a href="/crawl" class="nav-link text-white {{ 'active' if active_page=='crawling_media' else ''}}">
                            <i class="fa-regular fa-newspaper"></i>
                            Crawling Media
                        </a>
                    </li>
                    <li>
                        <a href="/sentiment" class="nav-link text-white {{ 'active' if active_page=='sentiment_media' else ''}}">
                            <i class="fa-regular fa-newspaper"></i>
                            Sentiment Media
                        </a>
                    </li>
                    <!-- check if the session role is admin -->
                    {% if session['user_role'] == 'admin' %}
                        <li>
                            <a href="/user" class="nav-link text-white {{ 'active' if active_page=='user' else ''}}">
                                <i class="fa-solid fa-user"></i>
                                Users
                            </a>
                        </li>
                    {% endif %}
                </ul>
                <hr />
                <div class="dropdown">
                    <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                        <!-- <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2" /> -->
                        <strong>{{ session['user_first_name'] }}</strong>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                        <!-- <li><a class="dropdown-item" href="#">New project...</a></li>
                        <li><a class="dropdown-item" href="#">Settings</a></li>
                        <li><a class="dropdown-item" href="#">Profile</a></li>
                        <li><hr class="dropdown-divider" /></li> -->
                        <li><a class="dropdown-item" href="/logout">Sign out</a></li>
                    </ul>
                </div>
            </div>
            
            
            <div class="container-fluid overflow-auto">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }} d-flex justify-content-between">
                                {{ message }}
                                <!-- button x for hide the alert -->
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                <div class="container my-5">
                    <h2>{% block title %}{% endblock %}</h2>
                </div>
                {% block content %}
                
                {% endblock %}
            </div>
        </main>

        <!-- <script src="sidebars.js"></script> -->
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://kit.fontawesome.com/c621075835.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
        <script src="{{ url_for('static', filename='js/sidebar.js') }}"></script>
        {% block scripts %}
        {% endblock %}
    </body>
</html>

flask/website/templates/baseauth.html
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="" />
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors" />
        <meta name="generator" content="Hugo 0.84.0" />
        <title>Sidebars · Bootstrap v5.0</title>

        <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sidebars/" />

        <!-- Bootstrap core CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

        <!-- Favicons -->
        <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180" />
        <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png" />
        <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png" />
        <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json" />
        <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3" />
        <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico" />
        <meta name="theme-color" content="#7952b3" />

        <style>
            .bd-placeholder-img {
                font-size: 1.125rem;
                text-anchor: middle;
                -webkit-user-select: none;
                -moz-user-select: none;
                user-select: none;
            }

            @media (min-width: 768px) {
                .bd-placeholder-img-lg {
                    font-size: 3.5rem;
                }
            }
        </style>

        <!-- Custom styles for this template -->
        <!-- <link href="sidebars.css" rel="stylesheet" /> -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/sidebar.css') }}">
    </head>
    <body>

        <main>
            <div class="d-flex flex-column flex-shrink-0 p-3 text-white justify-content-center align-items-center" style="width: 31.5625rem; background-color: #1C2D5B;">
                <img src="{{ url_for('static', filename='img/logo.png') }}" alt="" style="width: 10.5rem;height: 5rem;flex-shrink: 0;" class="mb-4">
                <img src="{{ url_for('static', filename='img/logo-text.png') }}" alt="" style="width: 27.3125rem;
                height: 7.125rem;
                flex-shrink: 0;">
            </div>
            
            <div class="container-fluid overflow-auto">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }} d-flex justify-content-between">
                                {{ message }}
                                <!-- button x for hide the alert -->
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                <div class="row justify-content-center align-items-center min-vh-100">
                    <div class="col-md-6">
                        <div class="card shadow-lg p-4 mb-5 bg-white rounded">
                            <div class="card-body">
                                <!-- Logo -->
                                <h3 class="font-weight-light mb-3" style="color: #1C2D5B;">{% block title %}Login{% endblock %}</h3>
                                <!-- Login Form -->
                                {% block content %}
                                {% endblock %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

        <!-- <script src="sidebars.js"></script> -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://kit.fontawesome.com/c621075835.js" crossorigin="anonymous"></script>
        <script src="{{ url_for('static', filename='js/sidebar.js') }}"></script>
        {% block scripts %}
        {% endblock %}
    </body>
</html>

flask/website/templates/crawl.html
{%extends "base.html"%}
{% set active_page = 'crawling_media' %}
{%block title%}Crawl{%endblock%}
{%block content%}
<div class="container mt-3">
    <div class="row">
        <div class="col">
            <input class="form-control mb-4" id="tableSearch" type="text" placeholder="Search">
        </div>
        <div class="col">
            <a href="/crawl_add" class="btn btn-primary float-end">
                Add Media
            </a>
        </div>
    </div>

    <!-- Table -->
    <div>
        <table class="table">
            <thead>
                <tr class="rounded-top">
                    <th style="background-color: #1C2D5B; border-radius: 10px 0 0 0;" class="text-light" scope="col">No</th>
                    <th style="background-color: #1C2D5B;" class="text-light" scope="col">Judul</th>
                    <th style="background-color: #1C2D5B;" class="text-light" scope="col">Tanggal</th>
                    <th style="background-color: #1C2D5B;" class="text-light" scope="col">Link</th>
                    <th style="background-color: #1C2D5B;" class="text-light" scope="col">Penulis</th>
                    <th style="background-color: #1C2D5B;" class="text-light" scope="col">News Value</th>
                    <th style="background-color: #1C2D5B;" class="text-light" scope="col">Detail</th>
                    <th style="background-color: #1C2D5B;" class="text-light" scope="col">Ringkasan</th>
                    <th style="background-color: #1C2D5B; border-radius: 0 10px 0 0;" class="text-light" scope="col">Media</th>
                </tr>
            </thead>
            <tbody id="myTable">
                {%for crawl in crawl_data%}
                <tr>
                    <th scope="row">{{loop.index}}</th>
                    <td>{{crawl.title}}</td>
                    <td>{{crawl.news_date}}</td>
                    <td><a href="{{crawl.link}}" target="_blank">Link</a></td>
                    <td>{{crawl.author}}</td>
                    <td>{{"{:,.2f}".format(crawl.news_value)}}</td>
                    <!-- <td>{{crawl.news_value}}</td> -->
                    <td>{{crawl.detail}}</td>
                    <td>{{crawl.summary}}</td>
                    <td>{{crawl.media}}</td>
                </tr>
                {%endfor%}
            </tbody>
        </table>
    </div>
    
</div>
{%endblock%}

flask/website/templates/crawladd.html
{%extends "base.html"%}
{% set active_page = 'crawling_media' %}

{%block style%}
<style>
    /* Loading Overlay Styles */
    #loading-overlay {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: rgba(0, 0, 0, 0.5);
        color: white;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        z-index: 9999;
    }
    #loading-overlay .spinner-border {
        width: 3rem;
        height: 3rem;
    }
    #loading-overlay p {
        margin-top: 10px;
        font-size: 1.2rem;
    }
</style>
{%endblock%}

{%block title%}Crawl{%endblock%}
{%block content%}
<div class="container mt-5">
    <form action="{{ url_for('views.crawl_add') }}" method="post" id="crawlForm">
        <div class="row mb-3">
            <div class="col">
                <label for="startDate">Start Date</label>
                <input type="date" class="form-control" id="startDate" name="start_date" />
            </div>
            <div class="col">
                <label for="endDate">End Date</label>
                <input type="date" class="form-control" id="endDate" name="end_date" />
            </div>
        </div>

        <div>
            <label class="form-label">Media Berita</label>
            <select class="form-select" id="multiple-select-field" multiple data-placeholder="Choose anything" name="media" id="media">
                <option value="detikoto">DetikOto</option>
                <option value="antara">Antara</option>
            </select>
        </div>

        <div class="form-group mb-4">
            <label class="form-label">Keyword</label>
            <select class="form-select" id="multiple-select-keyword" multiple data-placeholder="Choose anything" name="keyword" id="keyword">
                <option value="hyundai">Hyundai</option>
                <option value="hyundai+gowa">Hyundai Gowa</option>
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

<!-- Loading Overlay -->
<div id="loading-overlay" class="d-none">
    <div class="spinner-border text-primary" role="status">
        <span class="visually-hidden">Loading...</span>
    </div>
    <p>Loading, please wait...</p>
</div>

{%endblock%}

{%block scripts%}
<script>
    $( '#multiple-select-field' ).select2( {
        theme: "bootstrap-5",
        width: $( this ).data( 'width' ) ? $( this ).data( 'width' ) : $( this ).hasClass( 'w-100' ) ? '100%' : 'style',
        placeholder: $( this ).data( 'placeholder' ),
        closeOnSelect: false,
    });
    $( '#multiple-select-keyword' ).select2( {
        theme: "bootstrap-5",
        width: $( this ).data( 'width' ) ? $( this ).data( 'width' ) : $( this ).hasClass( 'w-100' ) ? '100%' : 'style',
        placeholder: $( this ).data( 'placeholder' ),
        closeOnSelect: false,
    });

    // Show loading overlay when form is submitted
    $('#crawlForm').on('submit', function() {
        $('#loading-overlay').removeClass('d-none');  // Show the loading overlay
    });
</script>
{%endblock%}

flask/website/templates/home copy.html
{%extends "base.html"%}
{% set active_page = 'home' %}
{%block title%}Dashboard{%endblock%}
{%block content%}
<div class="container">
    <div class="row mb-3">
        <!-- create form filter -->
        <div class="col-md-12">
            <form action="" method="post">
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <input type="date" name="tanggal" id="tanggal" class="form-control" placeholder="Tanggal">
                        </div>
                    </div>
                    <div class="col">
                        <button type="submit" class="btn btn-primary">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="row">
                <div class="col">
                    <div class="card shadow-lg mb-5 rounded">
                        <div class="card-header bg-white">
                            <h6 class="card-title">News Value</h6>
                        </div>
                        <div class="card-body">
                            <!-- home_data["news_value"] is so big so i need you to cut million and change it to Jt -->
                            <h1 class="font-weight-light mb-3">{{"{:,.0f}".format(home_data["sum_news_value"]/1000000)}} Jt</h1>
                            <!-- <h1 class="font-weight-light mb-3">14,744</h1> -->
                        </div>
                        <div class="card-footer bg-white">
                            <div class="row">
                                <div class="col-5 pe-0"><p class="text-success">+13,6%</p></div>
                                <div class="col-7 p-0"><p>from last month</p></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card shadow-lg mb-5 bg-white rounded">
                        <div class="card-header bg-white">
                            <h6 class="card-title">Jumlah Pemberitaan</h6>
                        </div>
                        <div class="card-body">
                            <h1 class="font-weight-light mb-3">{{home_data["count_news"]}}</h1>
                        </div>
                        <div class="card-footer bg-white">
                            <div class="row">
                                <div class="col-5 pe-0"><p class="text-success">+13,6%</p></div>
                                <div class="col-7 p-0"><p>from last month</p></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
        <div class="col-md-6">
            <div class="card shadow-lg mb-5 bg-white rounded">
                <div class="card-header">
                    <h6 class="card-title">Tren Pemberitaan</h6>
                </div>
                <div class="card-body">
                    <img src="data:image/png;base64,{{ plot_pemberitaan }}" alt="" class="w-100">
                </div>
            </div>
        </div>
    </div>
    
    <div class="row justify-content-center align-items-center">
        <div class="col-md-6">
            <div class="card shadow-lg mb-5 bg-white rounded">
                <div class="card-header">
                    <h6 class="card-title">Top Media Rangking</h6>
                </div>
                <div class="card-body">
                    <img src="data:image/png;base64,{{ plot_media }}" alt="" class="w-100">
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card shadow-lg mb-5 bg-white rounded">
                <div class="card-header">
                    <h6 class="card-title">Top Penulis Rangking</h6>
                </div>
                <div class="card-body">
                    <img src="data:image/png;base64,{{ plot_author }}" alt="" class="w-100">
                </div>
            </div>
        </div>
    </div>
</div>

{%endblock%}

flask/website/templates/home.html
{%extends "base.html"%}
{% set active_page = 'home' %}
{%block title%}Dashboard{%endblock%}
{%block content%}
<div class="container">
    <div class="row mb-3">
        <!-- create form filter -->
        <div class="col-md-12">
            <form action="" method="post">
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <input type="date" name="tanggal" id="tanggal" class="form-control" placeholder="Tanggal">
                        </div>
                    </div>
                    <div class="col">
                        <button type="submit" class="btn btn-primary">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="row">
                <div class="col">
                    <div class="card shadow-lg mb-5 rounded">
                        <div class="card-header bg-white">
                            <h6 class="card-title">News Value</h6>
                        </div>
                        <div class="card-body">
                            <!-- home_data["news_value"] is so big so i need you to cut million and change it to Jt -->
                            <h1 class="font-weight-light mb-3">{{"{:,.0f}".format(home_data["sum_news_value"]/1000000)}} Jt</h1>
                            <!-- <h1 class="font-weight-light mb-3">14,744</h1> -->
                        </div>
                        <div class="card-footer bg-white">
                            <div class="row">
                                <div class="col-5 pe-0"><p class="text-success">+13,6%</p></div>
                                <div class="col-7 p-0"><p>from last month</p></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card shadow-lg mb-5 bg-white rounded">
                        <div class="card-header bg-white">
                            <h6 class="card-title">Jumlah Pemberitaan</h6>
                        </div>
                        <div class="card-body">
                            <h1 class="font-weight-light mb-3">{{home_data["count_news"]}}</h1>
                        </div>
                        <div class="card-footer bg-white">
                            <div class="row">
                                <div class="col-5 pe-0"><p class="text-success">+13,6%</p></div>
                                <div class="col-7 p-0"><p>from last month</p></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
        <div class="col-md-6">
            <div class="card shadow-lg mb-5 bg-white rounded">
                <div class="card-header">
                    <h6 class="card-title">Tren Pemberitaan</h6>
                </div>
                <div class="card-body">
                    <img src="data:image/png;base64,{{ plot_pemberitaan }}" alt="" class="w-100">
                </div>
            </div>
        </div>
    </div>
    
    <div class="row justify-content-center align-items-center">
        <div class="col-md-6" style="margin-top: -30rem;">
            <div class="card shadow-lg mb-5 bg-white rounded">
                <div class="card-header">
                    <h6 class="card-title">Top Media Rangking</h6>
                </div>
                <div class="card-body">
                    <img src="data:image/png;base64,{{ plot_media }}" alt="" class="w-100">
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card shadow-lg mb-5 bg-white rounded">
                <div class="card-header">
                    <h6 class="card-title">Top Penulis Rangking</h6>
                </div>
                <div class="card-body">
                    <img src="data:image/png;base64,{{ plot_author }}" alt="" class="w-100">
                </div>
            </div>
        </div>
    </div>
</div>

{%endblock%}